<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\Ports\DrivenPorts\" />
    <Folder Include="Domain\Events\" />
    <Folder Include="Domain\Exceptions\" />
    <Folder Include="Domain\Services\" />
    <Folder Include="Domain\ValueObjects\" />
  </ItemGroup>

</Project>
